### ISSUE TITLE
checkscript/edit failures with: `NO "null"`

### ISSUE THREAD

**Issue by rnkn** [philpennock/sieve-connect#15]
Hello,

Thank you for making this program, it certainly gives me the illusion of power over my mail :)

I'm running into an issue when trying `checkscript` or `edit` on any sieve script, which returns:

    CHECKSCRIPT failed: NO "null"

I have a few rules in a `rules.sieve` on the server (created via a web UI). They've been working okay for a few years. I receive the above failure when I:

- `edit` the script and save with changes
- `edit` the script, save with no changes
- `edit` the script, deleting everything, saving an empty file
- `download` the script then run `checkscript rules.sieve`

All local commands seem to work fine, so I assume this is a problem with the server?

Thanks!

**Comment by philpennock** [comment]
Indeed, this is sieve-connect reporting back the server's response, so the server is saying that CHECKSCRIPT failed, which suggests a problem with the contents of the script.  sieve-connect can't help you here, sorry.

**Comment by rnkn** [comment]
Thanks!
