### ISSUE TITLE
Replace use of deprecated module IO::Socket::INET6 with IO:Socket::IP.

### ISSUE THREAD

**Issue by dbevans** [philpennock/sieve-connect#16]
The maintainer of IP::Socket::INET6 has indicated 'that it is deprecated and no longer suitable for use'.

Suggest updating sieve-connect to use its recommended replacement IO::Socket::IP.

See https://metacpan.org/pod/IO::Socket::INET6, https://metacpan.org/pod/IO::Socket::IP

Thanks

**Comment by philpennock** [comment]
Thanks for the report.  Fixed, please test.

**Comment by dbevans** [comment]
Testing now. Looks good at first blush. Will let you know if anything turns up.  Thanks for the quick response.
