### ISSUE TITLE
error handling  in non interactive use

### ISSUE THREAD

**Issue by jraschke** [philpennock/sieve-connect#6]
Hallo,

thanks for the sieve-connect tool,

I use it in bash scripts and found out  the error behaviour isn't consistent.

Sometimes you get return code <> 0, the expected behaviour
but othertimes you  get return code = 0 and an error message on stderr
or is start an interactive shell and wait for input from stdin

```
test@test4:~ >  echo password |  sieve-connect -s server -u user  --passwordfd 0  --localsieve --remotesieve sieve --upload
unable to read "--remotesieve": No such file or directory
test@test4:~ > echo $?
2

test@test4:~ >  echo password |  sieve-connect -s server -u user  --passwordfd 0  --localsieve /tmp/sieve_local --check 
CHECKSCRIPT failed: NO {101}
line 4: error: expecting ',' or end of string list ']', but found identifier.
error: parse failed.

test@test4:~ > echo $?
0

test@test4:~ >  echo password |  sieve-connect -s server -u user  --passwordfd 0  --localsieve --check 
ReadLine support enabled.
> 
```

my suggestion is another command line option like "--batch" or "--strict" 
if set then no interactive shell is startet, every waring turns to an error,

another point

If I use mutiple action option like  check upload activate only the last last "action" is executed
no warning is printed.
It would be nice, if the options are put to an command queue in order of their appearence
and then executed one ather the other, so you have to call the sieve-connect only once.

greeting
Juergen

**Comment by philpennock** [comment]
Thanks for the report, will investigate.

**Comment by AlexanderS** [comment]
@jraschke You can use `--exec` to supply a *script* with multiple commands to execute multiple actions in sequence within one connection.

**Comment by philpennock** [comment]
I believe that I have fixed this; worked for my simple test.

I'll probably cut 0.88 very soon (one more issue to tackle) with the expectation that I'm making breaking changes, so 0.89 may follow shortly thereafter if you spot any corner cases which I've missed!

Thanks, both for the report and for your patience.
