### ISSUE TITLE
Example for using --passwordfd ?

### ISSUE THREAD

**Issue by l8gravely** [philpennock/sieve-connect#8]
Phil,
Do you have an exmaple of how you would use --passwordfd in a script or makefile to help manage updates to sieve script(s) on a server?

**Comment by philpennock** [comment]
I didn't, as I normally use GSSAPI and so never have to worry about passwords in the tooling, but I just whipped this up.  Biggest problem is that plain `sh`, unlike `zsh`, doesn't (appear to) let a variable hold a file-descriptor number for the redirection setup, so I just hard-coded one.

```sh
#!/bin/sh -eu

usercode="frederic"
password_src="./stored.password"
p_fd=5

exec sieve-connect --authmech digest-md5 \
  "--user=$usercode" --passwordfd=5 \
  "$@" \
  5<"$password_src"
```

Invoke with args; `--debug` may help too.
```
% ./wrap-sc --list
[...]
```

* Drop `--user=...` if it's the same usercode as the locally running account.
* If you hold the password in memory, in a script, then use bash or zsh and a "here-string", such that it's `5<<<"$password"`
* In Python, to use `subprocess` you need to be using Python3 so that you can use the `pass_fds` key in the class constructor
* My Perl is very rusty; when I last used it, `IPC::Run` was the decent tool for running external commands and it's _probably_ something like, untested:
    ```perl
    $h = start ['sieve-connect', '--passwordfd=5', ...], '5<pipe', \*PASS, '>pipe', \*OUT
      or die "sieve-connect failed: $?\n";
    print PASS "the_password\n";
    close PASS;
    foreach (<OUT>) { do_something($_) }
    ```

Does that answer your question?

**Comment by l8gravely** [comment]
Interesting.  I need to learn more about setting up GSSAPI in my
setup.  Mostly I have home servers which talk to my VS hosted by
digital ocean for email of my stoffel.org domain.  Been a fun job
setting it up, but more complicated than it really needs to be in some
ways.

It would be nice if you could expand the docs a bit with examples of
how to do some automated updates.  I'm just using a makefile to
download, edit and push it back up, but I hate having to re-type my
password each time.  

Thanks for the quick patch!

Looks like the Steelers will "squish the fish" as us Pats fans
say... :-)


Phil> I didn't, as I normally use GSSAPI and so never have to worry about passwords
Phil> in the tooling, but I just whipped this up. Biggest problem is that plain sh,
Phil> unlike zsh, doesn't (appear to) let a variable hold a file-descriptor number
Phil> for the redirection setup, so I just hard-coded one.

Phil> #!/bin/sh -eu

Phil> usercode="frederic"
Phil> password_src="./stored.password"
Phil> p_fd=5

Phil> exec sieve-connect --authmech digest-md5 \
Phil>   "--user=$usercode" --passwordfd=5 \
Phil>   "$@" \
Phil>   5<"$password_src"

Phil> Invoke with args; --debug may help too.

Phil> % ./wrap-sc --list
Phil> [...]

Phil>   • Drop --user=... if it's the same usercode as the locally running account.
Phil>   • If you hold the password in memory, in a script, then use bash or zsh and a
Phil>     "here-string", such that it's 5<<<"$password"
Phil>   • In Python, to use subprocess you need to be using Python3 so that you can
Phil>     use the pass_fds key in the class constructor
Phil>   • My Perl is very rusty; when I last used it, IPC::Run was the decent tool
Phil>     for running external commands and it's probably something like, untested:

Phil>     $h = start ['sieve-connect', '--passwordfd=5', ...], '5<pipe', \*PASS, '>pipe', \*OUT
Phil>       or die "sieve-connect failed: $?\n";
Phil>     print PASS "the_password\n";
Phil>     close PASS;
Phil>     foreach (<OUT>) { do_something($_) }

Phil> Does that answer your question?

Phil> —
Phil> You are receiving this because you authored the thread.
Phil> Reply to this email directly, view it on GitHub, or mute the thread.*

**Comment by philpennock** [comment]
Uh, I made no patch, I provided an example ... is there something that I should have changed?

**Comment by l8gravely** [comment]
Phil> Uh, I made no patch, I provided an example ... is there
Phil> something that I should have changed?

Nah... I'm just a moron busy doing laundry.  :-)

**Comment by philpennock** [comment]
Documentation updated with an example, simpler than the above.

**Comment by l8gravely** [comment]
>>>>> "Phil" == Phil Pennock <notifications@github.com> writes:

Phil> Documentation updated with an example, simpler than the above.

Thanks Phil!
